platform_homepage:
    path:     /
    defaults: { _controller: PlatformBundle:Platform:index }

platform_albums:
    path: /albums/{sort}.{choice}
    defaults: { _controller: PlatformBundle:Platform:albums, sort: alpha_asc, choice: null }
