<?php

namespace MMJBTL\PlatformBundle\Repository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{


    public function getAlbumsByName()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->orderBy('a.titreAlbum', 'ASC');
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getAlbumsPochettes($listAlbums) {
        foreach ($listAlbums as $album) {
            $image = stream_get_contents($album->getPochette());
        }
        $image = pack("H*", $image);
        $response = new \Symfony\Component\HttpFoundation\Response();
        $response->headers->set('Content-type', 'image/jpeg');
        $response->headers->set('Content-Transfer-Encoding', 'binary');
        $response->setContent($image);
        return $response;
    }
}
